name: Build and test
run-name: ${{ github.actor }} on ${{ github.ref }}
on: 
    push:
        branches:
            - main
            - ci
            - 'check/**'
    pull_request:
        branches:
            - main
            - ci
            - 'check/**'
jobs:
    build:
        env:
          CCACHE_DIR: /home/runner/work/.ccache
          CCACHE_MAXSIZE: 1G
        runs-on: ${{matrix.os}}
        strategy:
            fail-fast: false

            matrix:
                os: [ubuntu-latest]
                build_type: [Debug, Release]
        steps:
            - uses: actions/checkout@v4
              with: 
                submodules: 'recursive'
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10'
                cache: 'pip'
            - name: Checkout protobuf
              uses: actions/checkout@v4
              with:
                repository: protocolbuffers/protobuf
                path: 'protobuf'
                ref: 'v3.18.3'
                submodules: 'recursive'
            - name: Install Tools
              run: |
                sudo apt-get update
                sudo apt-get install  -y gcc g++ cmake ninja-build ccache
                pip install -r 3rdparty/onnx-mlir/requirements.txt
            - name: Install Protobuf
              run: |
                sh utils/build-protobuf.sh
            - name: Install ONNX
              working-directory: 3rdparty/onnx-mlir/third_party/onnx
              run: python3 -m pip install -v .
            - name: Create CCache dir
              run: mkdir -p /home/runner/work/.ccache
            - name: Restore CCache 
              id: restore-ccache
              uses: actions/cache/restore@v3
              with:
                path: /home/runner/work/.ccache
                key: ccache-${{ matrix.build_type }}-${{ github.ref_name }}
                restore-keys: |
                    ccache-${{ matrix.build_type }}-${{ github.ref_name }}
                    ccache-${{ matrix.build_type }}-
                    ccache-
            - name: Configure&Build LLVM CMake
              run: |
                sh utils/configure-llvm.sh
                sh utils/build-llvm.sh
              env:
                LLVM_CCACHE_MAXSIZE: 1G
            - name: Configure CMake
              run: cmake -G Ninja -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DUSE_CCACHE_BUILD=ON
            - name: Build
              run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}
            - name: Save CCache
              id: save-ccache
              uses: actions/cache/save@v3
              with:
                path: /home/runner/work/.ccache
                key: ccache-${{ matrix.build_type }}-${{ github.ref_name }}
                upload-chunk-size: 2048